// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIDGBNAXsLK-4SiJbpG5b65WJ0UBRvdt8',
    appId: '1:1069243076868:web:2dc1f54b159abd153a4051',
    messagingSenderId: '1069243076868',
    projectId: 'crosspat-a9156',
    authDomain: 'crosspat-a9156.firebaseapp.com',
    databaseURL: 'https://crosspat-a9156-default-rtdb.firebaseio.com',
    storageBucket: 'crosspat-a9156.appspot.com',
    measurementId: 'G-NPNPBGH9CK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChlR-XFN_LT8FyHxFEfnaK0o3QbtwSozY',
    appId: '1:1069243076868:android:59e3300d9fcb8e6f3a4051',
    messagingSenderId: '1069243076868',
    projectId: 'crosspat-a9156',
    databaseURL: 'https://crosspat-a9156-default-rtdb.firebaseio.com',
    storageBucket: 'crosspat-a9156.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuet1QTdt_gXKfCHVcXIg3n5YdjbBLN68',
    appId: '1:1069243076868:ios:9b52d014316bda663a4051',
    messagingSenderId: '1069243076868',
    projectId: 'crosspat-a9156',
    databaseURL: 'https://crosspat-a9156-default-rtdb.firebaseio.com',
    storageBucket: 'crosspat-a9156.appspot.com',
    iosClientId: '1069243076868-p7omd669cht700ih100kbfvqp3tu6i3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.crosspat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuet1QTdt_gXKfCHVcXIg3n5YdjbBLN68',
    appId: '1:1069243076868:ios:9b52d014316bda663a4051',
    messagingSenderId: '1069243076868',
    projectId: 'crosspat-a9156',
    databaseURL: 'https://crosspat-a9156-default-rtdb.firebaseio.com',
    storageBucket: 'crosspat-a9156.appspot.com',
    iosClientId: '1069243076868-p7omd669cht700ih100kbfvqp3tu6i3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.crosspat',
  );
}
